title: Ki's Blog
email: beomki69@gmail.com
description: Beom-Ki's Programming & Tech blog
author: Beom-Ki
baseurl: ""
url: "https://beomki69.github.io/"
timezone: Asia/Seoul

# Social Profiles
twitter_username:
github_username: beomki69
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: G-QX0RH1R50D # out your google-analytics code

# Build settings
markdown: kramdown
asset_url: /assets
kramdown:
  parse_block_html: true
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
